# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mock-ingress
  namespace: mockspace
spec:
  rules:
  - host: mock.service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mockservice
            port:
              number: 80