apiVersion: v1
kind: Secret
metadata:
  name: mocksecret
  namespace: mockspace
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  DB_PASSWORD: cGFzc3dvcmQ=  # "password" encoded in base64