apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mock
  namespace: mockspace
  labels:
    app:  mock
spec:
  selector:
    matchLabels:
      app: mockapi
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mockapi
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mockapi
        image:  mock:1.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: mockconfig
            #key: PORT    # we can inject specific key from configmap, but here we inject all keys
            #key: APP_ENV
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mocksecret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: mockport   # use named port here.
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: mockport   # use named port here.
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  8080   # this doesn't affect the real pod port. just metadata
          name:  mockport   # named port
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: mock-config
          mountPath: /app/config
          readOnly: true
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: mock-config
          configMap:
            name: mockconfig
            #items:
              # - key: config.json
      restartPolicy: Always